// ELEMENT IDCs

// main
#define IDC_ADMINPANEL_BACKGROUND		4325
#define IDC_ADMINPANEL_MAIN_TITLE		4425
#define IDC_ADMINPANEL_MADEBY			4346

// playerlist
#define IDC_ADMINPANEL_PLAYERLIST_TITLE		4429
#define IDC_ADMINPANEL_PLAYERLIST_LISTBOX	4825

// pip camera
#define IDC_ADMINPANEL_PLAYER_CAMDISPLAY_BACK		4360
#define IDC_ADMINPANEL_PLAYER_CAMDISPLAY_TITLE		4434
#define IDC_ADMINPANEL_PLAYER_CAMDISPLAY			4526
#define IDC_ADMINPANEL_PLAYER_CAMDISPLAY_VIEWMODE	4946
#define IDC_ADMINPANEL_PLAYER_CAMDISPLAY_VISMODE	4947

// map
#define IDC_ADMINPANEL_MAP					4525
#define IDC_ADMINPANEL_MAP_DESCRIPTION		4339

// player info
#define IDC_ADMINPANEL_PLAYER_INFO_BACK				4326
#define IDC_ADMINPANEL_PLAYER_INFO_TITLE			4426
#define IDC_ADMINPANEL_PLAYER_INFO_NAME				4327
#define IDC_ADMINPANEL_PLAYER_INFO_GRID				4328
#define IDC_ADMINPANEL_PLAYER_INFO_SIDE				4331
#define IDC_ADMINPANEL_PLAYER_INFO_FPS				4342
#define IDC_ADMINPANEL_PLAYER_INFO_VEHICLE_INFO		4329

// group info
#define IDC_ADMINPANEL_PLAYER_GROUP_TITLE			4431
#define IDC_ADMINPANEL_PLAYER_GROUP_BACK			4340
#define IDC_ADMINPANEL_PLAYER_GROUP_GROUPNAME		4330
#define IDC_ADMINPANEL_PLAYER_GROUP_COMBO			5425
#define IDC_ADMINPANEL_PLAYER_GROUP_ASSIGNBUTTON	4937

// vehicle tools
#define IDC_ADMINPANEL_PLAYER_VEHICLE_TITLE		4428
#define IDC_ADMINPANEL_PLAYER_VEHICLE_BACK		4337
#define IDC_ADMINPANEL_PLAYER_VEHICLE_DISMOUNT	4927
#define IDC_ADMINPANEL_PLAYER_VEHICLE_UNSTUCK	4928
#define IDC_ADMINPANEL_PLAYER_VEHICLE_REPAIR	4929
#define IDC_ADMINPANEL_PLAYER_VEHICLE_REFUEL	4930
#define IDC_ADMINPANEL_PLAYER_VEHICLE_REARM		4931
#define IDC_ADMINPANEL_PLAYER_VEHICLE_REPTEXT	4348
#define IDC_ADMINPANEL_PLAYER_VEHICLE_REFTEXT	4349
#define IDC_ADMINPANEL_PLAYER_VEHICLE_REATEXT	4350


// medical
#define IDC_ADMINPANEL_PLAYER_MEDICAL_TITLE		4427
#define IDC_ADMINPANEL_PLAYER_MEDICAL_BACK		4332
#define IDC_ADMINPANEL_PLAYER_MEDICAL_STATUS	4336
#define IDC_ADMINPANEL_PLAYER_MEDICAL_HEART		4333
#define IDC_ADMINPANEL_PLAYER_MEDICAL_BLDPRES	4334
#define IDC_ADMINPANEL_PLAYER_MEDICAL_BLDVOL	4335
#define IDC_ADMINPANEL_PLAYER_MEDICAL_PAIN		4347
#define IDC_ADMINPANEL_PLAYER_MEDICAL_WAKEUP	4925
#define IDC_ADMINPANEL_PLAYER_MEDICAL_FULLHEAL	4926

// admin tools
#define IDC_ADMINPANEL_ADMIN_TITLE			4432
#define IDC_ADMINPANEL_ADMIN_BACK			4341
#define IDC_ADMINPANEL_ADMIN_KICK			4938
#define IDC_ADMINPANEL_ADMIN_BAN_BACK		4351
#define IDC_ADMINPANEL_ADMIN_BAN			4939
#define IDC_ADMINPANEL_ADMIN_SPECTATE_BACK	4359
#define IDC_ADMINPANEL_ADMIN_SPECTATE		4935
#define IDC_ADMINPANEL_ADMIN_ZEUS_BACK		4353
#define IDC_ADMINPANEL_ADMIN_ZEUS			4942
#define IDC_ADMINPANEL_ADMIN_SERVERLOCK		4940

// admin stats
#define IDC_ADMINPANEL_ADMIN_SERVERFPS		4443
#define IDC_ADMINPANEL_ADMIN_ACTIVEAI		4444

// utilities
#define IDC_ADMINPANEL_UTILITIES_TITLE			4430
#define IDC_ADMINPANEL_UTILITIES_BACK			4338
#define IDC_ADMINPANEL_UTILITIES_GODMODE_BACK	4354
#define IDC_ADMINPANEL_UTILITIES_GODMODE		4932
#define IDC_ADMINPANEL_UTILITIES_INFAMMO_BACK	4352
#define IDC_ADMINPANEL_UTILITIES_INFAMMO		4933
#define IDC_ADMINPANEL_UTILITIES_GHOST_BACK		4356
#define IDC_ADMINPANEL_UTILITIES_GHOST			4934
#define IDC_ADMINPANEL_UTILITIES_ARSENAL		4936

// mission tools
#define IDC_ADMINPANEL_MISSION_TITLE		4433
#define IDC_ADMINPANEL_MISSION_BACK			4345
#define IDC_ADMINPANEL_MISSION_ENDCOMBO		5426
#define IDC_ADMINPANEL_MISSION_ENDBUTTON	4941

// remote exec
#define IDC_ADMINPANEL_REMOTEEXEC_EDITBOX			4725
#define IDC_ADMINPANEL_REMOTEEXEC_EXECBUTTON_BACK	4355
#define IDC_ADMINPANEL_REMOTEEXEC_EXECBUTTON		4943
#define IDC_ADMINPANEL_REMOTEEXEC_SERVEREXEC_BACK	4358
#define IDC_ADMINPANEL_REMOTEEXEC_SERVEREXEC		4944
#define IDC_ADMINPANEL_REMOTEEXEC_LOCALEXEC_BACK	4357
#define IDC_ADMINPANEL_REMOTEEXEC_LOCALEXEC			4945
#define IDC_ADMINPANEL_REMOTEEXEC_PREV				4948
#define IDC_ADMINPANEL_REMOTEEXEC_NEXT				4949
